### ISSUE TITLE
Insufficient permission

### ISSUE THREAD

**Issue by EarlyEdition** [programarivm/programarivm#1]
Hi @programarivm,

Thanks for inviting me to your organization. I wanted to create a repository on ChesslaBlab. But unfortunately, I couldn't because of **insufficient permission**. I would like to ask you permission to create a repository.

Cheers,
Gary

**Comment by programarivm** [comment]
Thank you @EarlyEdition for your interest in the ChesslaBlab organization! Sounds like a plan, let me just point out that it'd be more convenient to open an issue on a specific repo for better discussion and related questions.

**Comment by EarlyEdition** [comment]
Hi again Jordi, Unfortunately, Today the unexpected happened. I am blocked from the official-stockfish organization and cannot comment because of this content: https://github.com/official-stockfish/Stockfish/discussions/5230#discussioncomment-9447980

So are you still interested in developing a repository with me? Please let me know if you have any problems with it.

**Comment by programarivm** [comment]
Well, I am not too sure why that happened.  Let me insist that it'd be convenient to open an issue on a specific repo for better discussion and related questions rather than commenting on my profile.

You may want to look at https://github.com/chesslablab/engine/issues/2

**Comment by EarlyEdition** [comment]
OK, I close this issue now.
